

pushpull:
  class:     'PushPullGenerator'
  nmodes:     54
  vect_amplitude:  [50,50,50,50,50,50,50,50,50,50,
                      50,50,50,50,50,50,50,50,50,50,
                      50,50,50,50,50,50,50,50,50,50,
                      50,50,50,50,50,50,50,50,50,50,
                      50,50,50,50,50,50,50,50,50,50,
                      50,50,50,50]
  outputs: ['output']

main_override:
  total_time:  0.108

prop_override:
  inputs:
    common_layer_list: ['pupilstop',
                  'dm.out_layer']

dm_override:
  sign: 1
  inputs:
      in_command: 'pushpull.output'

detector_override:
  photon_noise:      False
  readout_noise:     False


im_calibrator:
  class: 'ImCalibrator'
  nmodes: 54
  im_tag:     'scao_intmat'
  overwrite: True
  inputs:
    in_slopes: 'slopec.out_slopes'
    in_commands: 'pushpull.output'
  outputs: ['out_intmat']


rec_calibrator:
  class: 'RecCalibrator'
  nmodes: 54
  rec_tag:     'scao_recmat'
  overwrite: True
  inputs:
    in_intmat: 'im_calibrator.out_intmat'


pixels_disp:
  class:            'PixelsDisplay'
  inputs:
    pixels:      "detector.out_pixels"
  title:            "Pixels"
  figsize:       [8, 6]  # Default size in inches

remove: ['atmo', 'rec','control']
 


