

pupil_calibrator:
  class: 'DynamicPyrPupdataCalibrator'
  dt: 0.1
  thr1: 0.1
  thr2: 0.25
  output_tag:        'scao_pupdata'
  inputs:
    in_i: 'pyramid.out_i'
    in_thr1:  'terminal.thr1'
    in_thr2:  'terminal.thr2'
    in_save: 'terminal.save'

seeing_override:
  constant:    0.0
  
main_override:
  total_time:  -1

pyramid_override:
  mod_amp:           10.0                     # Modulation radius (in lambda/D units)

display:
  class: 'PixelsPupDisplay'
  inputs:
    in_pupdata: 'pupil_calibrator.out_pupdata'
    in_params: 'pupil_calibrator.out_params'
    in_pixels: 'detector.out_pixels'

terminal:
  class: 'TerminalInput'
  output_list: ['thr1', 'thr2', 'save']

remove: ['slopec', 'rec','control', 'dm', 'psf']
 

