

pushpull:
  class:     'PushPullGenerator'
  ncycles:    2
  nmodes:     700
  vect_amplitude_data:  'data50_1127'
  outputs: ['output']

main_override:
  total_time:  1.4 # 2 (push-pull) * 700 (modes) * 1e-3 (time per mode) = 1.4s

prop_override:
  inputs:
    common_layer_list: ['pupilstop',
                  'dm.out_layer']

source_on_axis_override:
  polar_coordinates:  [0.0, 0.0]         # [arcsec, degrees] source polar coordinates
  magnitude:         7.0  

dm_override:
  sign: 1
  inputs:
      in_command: 'pushpull.output'


detector_override:
  dt:                0.001
  photon_noise:      False
  readout_noise:     False
  excess_noise:      False


im_calibrator_lo:
  class: 'ImCalibrator'
  nmodes: 700
  im_tag:     'eris_im'
  overwrite: True
  inputs:
    in_slopes: 'slopec.out_slopes'
    in_commands: 'pushpull.output'
  outputs: ['out_intmat']


rec_calibrator_lo:
  class: 'RecCalibrator'
  nmodes: 700
  rec_tag:     'eris_rec'
  overwrite: True
  inputs:
    in_intmat: 'im_calibrator_lo.out_intmat'


remove: ['atmo',
  'modalrec',
  'integrator',
  'psf',
  ]
