

pushpull:
  class:     'PushPullGenerator'
  ncycles:    2
  nmodes:     10
  vect_amplitude_data:  'data50_1127'
  outputs: ['output']

main_override:
  time_step: 0.001
  total_time:  0.040 # 2 (push-pull) * 10 (modes) * 1e-3 (time per mode) = 0.040s


prop_override:
  inputs:
    common_layer_list: ['pupilstop',
                  'dm.out_layer']


source_on_axis_override:
  polar_coordinates:  [0.0, 0.0]         # [arcsec, degrees] source polar coordinates
  magnitude:         7.0  


dm_override:
  sign: 1
  inputs:
      in_command: 'pushpull.output'


detector_lgs_override:
  dt:                0.001
  photon_noise:      False
  readout_noise:     False
  excess_noise:      False


detector_lo_override:
  dt:                0.001
  photon_noise:      False
  readout_noise:     False
  excess_noise:      False


slopec_lo_override:
  weightedPixRad:    12
  windowing:         True
  thr_value:         0


im_calibrator_lo:
  class: 'ImCalibrator'
  nmodes: 5
  im_tag:     'eris_im_lo'
  overwrite: True
  inputs:
    in_slopes: 'slopec_lo.out_slopes'
    in_commands: 'pushpull.output'
  outputs: ['out_intmat']


rec_calibrator_lo:
  class: 'RecCalibrator'
  nmodes: 2
  rec_tag:     'eris_rec_lo'
  overwrite: True
  inputs:
    in_intmat: 'im_calibrator_lo.out_intmat'


im_calibrator_truth:
  class: 'ImCalibrator'
  nmodes: 10
  im_tag:     'eris_im_truth'
  overwrite: True
  inputs:
    in_slopes: 'slopec_lo.out_slopes'
    in_commands: 'pushpull.output'
  outputs: ['out_intmat']


rec_calibrator_truth:
  class: 'RecCalibrator'
  nmodes: 10
  rec_tag:     'eris_rec_truth'
  overwrite: True
  inputs:
    in_intmat: 'im_calibrator_truth.out_intmat'


remove: ['atmo',
  'sh_lgs',
  'detector_lgs',
  'slopec_lgs',
  'modalrec_lgs',
  'modalrec_lo',
  'modalrec_truth',
  'integrator_truth',
  'subtract_truth',
  'integrator_lgs',
  'integrator_lo',
  'slicer_lgs',
  'modal_combination',
  'psf',
  ]
