

pushpull:
  class:     'PushPullGenerator'
  nmodes:     1127
  vect_amplitude_data:  'data50_1127'
  outputs: ['output']

main_override:
  time_step: 0.001
  total_time:  2.254 # 2 (push-pull) * 1127 (modes) * 1e-3 (time per mode) = 2.254s

prop_override:
  inputs:
    common_layer_list: ['pupilstop',
                  'dm.out_layer']

dm_override:
  sign: 1
  inputs:
      in_command: 'pushpull.output'

detector_lgs_override:
  dt:                0.001
  photon_noise:      False
  readout_noise:     False
  excess_noise:      False


im_calibrator:
  class: 'ImCalibrator'
  nmodes: 700
  im_tag:     'eris_im_lgs'
  overwrite: True
  inputs:
    in_slopes: 'slopec_lgs.out_slopes'
    in_commands: 'pushpull.output'
  outputs: ['out_intmat']


rec_calibrator:
  class: 'RecCalibrator'
  nmodes: 700
  rec_tag:     'eris_rec_lgs'
  overwrite: True
  inputs:
    in_intmat: 'im_calibrator_lo.out_intmat'


remove: ['atmo',
  'modalrec_lgs',
  'sh_lo',
  'detector_lo',
  'slopec_lo',
  'modalrec_lo',
  'modalrec_truth',
  'integrator_truth',
  'subtract_truth',
  'integrator_lgs',
  'integrator_lo',
  'slicer_lgs',
  'modal_combination',
  'psf',
  ]
