#!/usr/bin/env python3
"""
Why the AVC plant estimate x=[PR,PI,lc,ls] fails to converge, in the BEST
possible case: no AO loop, no delay, no noise, frequency KNOWN and fixed, and
the measurement generated by the algorithm's own identity y = W^T x_true
(eq. 8 of Muradore et al.) -- zero model mismatch. Two experiments.
"""
import numpy as np

# true plant response P(j2pi f) and true single-frequency vibration
PR, PI = 0.127, -0.596          # ~ LPF plant at 47 Hz (|P|=0.61, -78 deg)
lc, ls = 1000.0, 0.0            # vibration cos/sin amplitude [nm]
x_true = np.array([PR, PI, lc, ls])

T, f, gx, theta_min = 1e-3, 47.0, 0.1, 1e-2

def theta_of(x):
    x1, x2, x3, x4 = x
    d = x1*x1 + x2*x2 + theta_min          # soft floor
    return -(x1*x3 - x2*x4)/d, -(x1*x4 + x2*x3)/d      # eq. 11

def W_of(alpha, thc, ths):
    c, s = np.cos(alpha), np.sin(alpha)
    return np.array([thc*c + ths*s, ths*c - thc*s, c, s])   # eq. 9

# ===================================================================
# EXPERIMENT A -- FROZEN regressor: build W from the TRUE theta and keep
# it fixed. The x-update is then purely linear, delta <- (I - gx T W W^T)
# delta, and the observability structure is exposed cleanly.
# ===================================================================
# small disturbance here so the (|theta|^2+1)-scaled observable loop gain
# stays in the stable range -- the rank structure is amplitude-independent
xA_true = np.array([PR, PI, 1.0, 0.0])
thc0, ths0 = theta_of(xA_true)
x = xA_true + np.array([0.5, -0.5, 0.3, -0.2])   # arbitrary initial offset
delta0 = x - xA_true
alpha, WWT = 0.0, np.zeros((4, 4))
N = 400000
for k in range(N):
    W = W_of(alpha, thc0, ths0)            # <-- theta FROZEN at truth
    y = W @ xA_true
    x = x - gx*T*W*(W @ x - y)
    alpha += 2*np.pi*f*T
    if alpha > np.pi: alpha -= 2*np.pi
    if k >= N-20000: WWT += np.outer(W, W)
WWT /= 20000
eig = np.linalg.eigvalsh(WWT)
deltaf = x - xA_true

# the two analytic null directions of the frozen regressor
nA = np.array([1, 0, -thc0, -ths0])
nB = np.array([0, 1, -ths0,  thc0])
# project residual error onto observable vs unobservable subspace
Null = np.column_stack([nA/np.linalg.norm(nA), nB/np.linalg.norm(nB)])
Pnull = Null @ np.linalg.solve(Null.T@Null, Null.T)
res_unobs = np.linalg.norm(Pnull @ deltaf)
res_obs = np.linalg.norm(deltaf - Pnull @ deltaf)

print("="*68)
print("EXPERIMENT A  (frozen theta = truth; purely linear update)")
print("="*68)
print(f"initial |delta|                    = {np.linalg.norm(delta0):8.3f}")
print(f"final   |delta|  (x_hat - x_true)   = {np.linalg.norm(deltaf):8.3f}")
print(f"   ... its OBSERVABLE part          = {res_obs:8.3e}   (driven to 0)")
print(f"   ... its UNOBSERVABLE part        = {res_unobs:8.3f}   (frozen, never corrected)")
print(f"eigenvalues of avg W W^T            = "
      f"{eig[3]:.4f}, {eig[2]:.4f}, {eig[1]:.2e}, {eig[0]:.2e}")
print("   -> exactly two nonzero, two ZERO  => regressor is rank 2 for a")
print("      rank-4 state. A single sinusoid cannot excite all 4 axes.")
print(f"   check W W^T . nA = {np.linalg.norm(WWT@nA):.2e},  "
      f"W W^T . nB = {np.linalg.norm(WWT@nB):.2e}  (both ~0)")

# ===================================================================
# EXPERIMENT B -- REAL algorithm: recompute theta from the running x_hat
# each step (as the code does). The unobservable drift now feeds back
# through theta = f(x), and the 1/(x1^2+x2^2) coupling turns harmless
# drift into a runaway.
# ===================================================================
x = np.array([0.9*PR, 0.9*PI, 0.0, 0.0])    # seeded NEAR the true plant
alpha = 0.0
mags = []
for k in range(400000):
    thc, ths = theta_of(x)                  # <-- theta recomputed from x_hat
    W = W_of(alpha, thc, ths)
    y = W @ x_true
    x = x - gx*T*W*(W @ x - y)
    alpha += 2*np.pi*f*T
    if alpha > np.pi: alpha -= 2*np.pi
    if k % 40000 == 0:
        mags.append((k*T, np.hypot(x[0], x[1]), np.hypot(x[2], x[3])))

print()
print("="*68)
print("EXPERIMENT B  (real algorithm: theta recomputed from x_hat)")
print("="*68)
print(" t[s]   |plant est x1,x2|   |dist est x3,x4|")
for t, pm, dm in mags:
    print(f" {t:4.1f}   {pm:14.4f}   {dm:14.2f}")
print()
print("Plant estimate seeded at the TRUE value does NOT stay there: the")
print("unobservable drift + the 1/(x1^2+x2^2) coupling drives it away, with")
print("no noise, no delay and the exact frequency. Structural, not a bug.")

# ===================================================================
# EXPERIMENT C -- proposed fix: FREEZE the (unobservable) plant estimate
# x1,x2 at the calibrated value; adapt ONLY the disturbance x3,x4.
# ===================================================================
x = np.array([PR, PI, 0.0, 0.0])            # plant at calibrated value, frozen
alpha = 0.0
for k in range(400000):
    thc, ths = theta_of(x)
    W = W_of(alpha, thc, ths)
    y = W @ x_true
    err = W @ x - y
    # update x3,x4 only; x1,x2 held fixed
    x[2] -= gx*T*W[2]*err
    x[3] -= gx*T*W[3]*err
    alpha += 2*np.pi*f*T
    if alpha > np.pi: alpha -= 2*np.pi
    if k == 399999:
        errC = err
print()
print("="*68)
print("EXPERIMENT C  (fix: freeze plant x1,x2 at calibration, adapt x3,x4)")
print("="*68)
print(f"final disturbance estimate (x3,x4) = ({x[2]:.3f}, {x[3]:.3f})  "
      f"[true = ({lc:.1f}, {ls:.1f})]")
print(f"final prediction error |err|       = {abs(errC):.3e}")
print("-> converges to the true disturbance and nulls the error. Freezing")
print("   the unobservable plant axes removes the drift entirely.")
