"""Ten vibrations, ten AVC channels: the multi-mode demonstration.

One narrow-band vibration is injected into each of the first ten Zernike
modes, at a different frequency per mode, and one ``AVCSimplified`` channel
is assigned to each. The point is to check that the module works as a
per-mode canceller in a shared loop: the ten channels see the same WFS, the
same reconstructor and the same integrator, and their commands are summed
into the same DM.

Frequencies span 36-120 Hz, chosen with a minimum separation of 7 Hz and no
2:1 or 3:1 ratios between any pair, so that a harmonic generated by one
channel cannot land on another. Amplitudes fall geometrically from 80 nm on
tip to 15 nm on mode 9, which is both the way mechanical vibration usually
couples into an AO system and what keeps the summed excursion inside the
Shack-Hartmann linear range.

Stages
------
``calib``    multi-tone probe in closed loop -> plant gain and phase for
             every (mode, frequency) pair, written to ``avc_multimode_plant.json``
``baseline`` the same loop with the vibrations on and no AVC
``avc``      the same loop with the ten channels running

Usage::

    python run_avc_multimode.py                # all three, in order
    python run_avc_multimode.py calib          # just the calibration

Analysed by ``analyze_avc_multimode.py``.
"""
import json
import sys

import numpy as np
import yaml

N_MODES = 10

# One frequency per mode. Minimum separation 7 Hz; no pair within 2 Hz of a
# 2:1 or 3:1 ratio, so harmonics generated by the WFS nonlinearity of one
# channel do not fall into the passband of another.
FREQS = [36.0, 44.0, 59.0, 68.0, 76.0, 83.0, 92.0, 102.0, 111.0, 120.0]

# Geometric taper, 80 nm on tip down to 15 nm on mode 9.
AMPS = [80.0, 66.0, 55.0, 46.0, 38.0, 32.0, 26.0, 22.0, 18.0, 15.0]

GOMEGA = 0.05           # PLL rate; see the note in build_run_params
PROBE_AMP = 20.0        # [nm] small: the loop amplifies up to ~7x at 44 Hz
CALIB_SKIP = 1500       # [samples] transient dropped before the lock-in
PLANT_FILE = 'avc_multimode_plant.json'


# --------------------------------------------------------------------------
# parameter files
# --------------------------------------------------------------------------

def _vibrations(params, amps):
    """Point the vibration generator and its DM at the first N_MODES modes."""
    params['vib_wave']['amp'] = list(amps)
    params['vib_wave']['freq'] = list(FREQS)
    params['vib_dm']['idx_modes'] = list(range(N_MODES))
    return params


def build_calib_params():
    """Multi-tone probe: every mode probed at its own frequency, at once.

    The vibrations are off and the atmosphere is effectively off, so each
    mode's residual contains only the response to its own probe tone. One
    run therefore calibrates all ten channels.
    """
    p = yaml.safe_load(open('params_measure_plant.yml'))
    p['probe_wave']['amp'] = [PROBE_AMP] * N_MODES
    p['probe_wave']['freq'] = list(FREQS)
    p['probe_inserter']['slice_args'] = [[0, N_MODES], [0, N_MODES]]
    p = _vibrations(p, [0.0] * N_MODES)          # vibrations off
    p['data_store']['store_dir'] = './output/MM_calib'
    return p


def build_run_params(with_avc, plant=None):
    """The full loop, with or without the AVC channels."""
    if with_avc:
        p = yaml.safe_load(open('params_scao_avc_simplified.yml'))
        p['mode_slicer']['indices'] = list(range(N_MODES))
        avc = p['avc']
        avc.pop('plant_re', None)
        avc.pop('plant_im', None)
        avc['n_avc'] = N_MODES
        avc['freq'] = list(FREQS)
        # The single-mode demo used gomega = 0.2. That is too fast here: near
        # the waterbed peak the plant phase moves ~21 deg/Hz, so a PLL
        # excursion of a few Hz eats the whole 90 deg margin, and the 44 Hz
        # channel goes unstable (its estimate ran to 65 Hz). At 0.05 every
        # channel locks to within 0.01 Hz. See the report.
        avc['gomega'] = GOMEGA
        avc['plant_gain'] = [float(g) for g in plant['gain']]
        avc['plant_phase'] = [float(a) for a in plant['phase']]
        p['avc_inserter']['slice_args'] = [[0, N_MODES], [0, N_MODES]]
        p['data_store']['store_dir'] = './output/MM_avc'
    else:
        p = yaml.safe_load(open('params_scao_vibration_baseline.yml'))
        p['data_store']['store_dir'] = './output/MM_baseline'
    return _vibrations(p, AMPS)


# --------------------------------------------------------------------------
# calibration
# --------------------------------------------------------------------------

def measure_plant(run_dir):
    """Lock-in on the probe run: closed-loop command -> residual, per mode.

    Same convention as the single-mode harness documented in HOW_TO.md:
    P = <residual * e^{-i w t}> / <probe * e^{-i w t}>, over the steady part
    of the run.
    """
    import glob
    import os
    from astropy.io import fits

    rm = np.asarray(fits.getdata(os.path.join(run_dir, 'res_modes.fits')), dtype=float)
    pr = np.asarray(fits.getdata(os.path.join(run_dir, 'probe.fits')), dtype=float)
    if pr.ndim == 1:
        pr = pr[:, None]
    n = rm.shape[0]
    sl = slice(CALIB_SKIP, n)
    t = np.arange(n)[sl] * 1e-3

    gain, phase = [], []
    for i, f in enumerate(FREQS):
        ref = np.exp(-1j * 2 * np.pi * f * t)
        p = np.mean(rm[sl, i] * ref) / np.mean(pr[sl, i] * ref)
        gain.append(abs(p))
        phase.append(np.degrees(np.angle(p)))
    return {'freq': FREQS, 'gain': gain, 'phase': phase}


# --------------------------------------------------------------------------

def main(stages):
    import glob

    import specula
    specula.init(-1)
    from specula.simul import Simul

    def run(params, tag):
        path = f'/tmp/params_MM_{tag}.yml'
        yaml.safe_dump(params, open(path, 'w'))
        print(f'=== running {tag}', flush=True)
        Simul(path).run()

    if 'calib' in stages:
        run(build_calib_params(), 'calib')
        plant = measure_plant(sorted(glob.glob('output/MM_calib/*'))[-1])
        json.dump(plant, open(PLANT_FILE, 'w'), indent=2)
        print(f'\n  mode   f [Hz]      |P|     arg P [deg]')
        for i, f in enumerate(FREQS):
            print(f'{i:6d} {f:8.1f} {plant["gain"][i]:9.3f} {plant["phase"][i]:13.2f}')

    if 'baseline' in stages:
        run(build_run_params(False), 'baseline')

    if 'avc' in stages:
        plant = json.load(open(PLANT_FILE))
        run(build_run_params(True, plant), 'avc')


if __name__ == '__main__':
    order = ['calib', 'baseline', 'avc']
    requested = sys.argv[1:] or order
    unknown = [s for s in requested if s not in order]
    if unknown:
        raise SystemExit(f'unknown stage(s): {unknown}; choose from {order}')
    main([s for s in order if s in requested])
